config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  resources :hotels
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  has_many :rooms, :dependent => :destroy
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :hotel
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]

  def index
    @hotels = Hotel.all
  end

  def show
  end

  def new
    @hotel = Hotel.new
  end

  def edit
  end

  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: t('flash.hotel.create.notice') }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: t('flash.hotel.update.notice') }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url, notice: t('flash.hotel.remove.notice') }
    end
  end

  private
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    def hotel_params
      params.require(:hotel).permit(:name, :email, :address, :phone, :bio)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  def index
    @rooms = Room.all
  end

  def show
  end

  def new
    @room = Room.new
  end

  def edit
  end

  def create
    @room = Room.new(room_params)
    @room.hotel = Hotel.first

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: t('flash.room.create.notice') }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: t('flash.room.update.notice') }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: t('flash.room.remove.notice') }
    end
  end

  private
    def set_room
      @room = Room.find(params[:id])
    end

    def room_params
      params.require(:room).permit(:number, :floor)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/hotels/_form.html.erb
<%= form_for @hotel, :html => {:class => "form-horizontal"} do |f| %>
  <% if @hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>
      <ul>
      <% @hotel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: 'col-md-3 control-label' %>
    <div class="col-md-6">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: 'col-md-3 control-label' %>
    <div class="col-md-6">
      <%= f.text_field :email, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, class: 'col-md-3 control-label' %>
    <div class="col-md-6">
      <%= f.text_field :address, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone, class: 'col-md-3 control-label' %>
    <div class="col-md-6">
      <%= f.text_field :phone, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :bio, class: 'col-md-3 control-label' %>
    <div class="col-md-6">
      <%= f.text_field :bio, class: 'form-control' %>
    </div>
  </div>
  <%= f.submit t('actions.save'), class: 'btn btn-success col-md-3 col-md-offset-3' %>
  <%= link_to t('actions.back'), hotels_path, class: 'btn btn-default col-md-3' %>
<% end %>

app/views/hotels/edit.html.erb
<h1><% t('title.hotels.edit') %></h1>
<%= render 'form' %>

app/views/hotels/index.html.erb
<p id="notice"><%= notice %></p>
<h1><%= t('title.hotel.index') %></h1>
<%= link_to t('actions.new'), new_hotel_path, class: 'btn btn-primary' %>
<table class="table table-condensed">
  <thead>
    <tr>
      <th><%= t('activerecord.attributes.hotel.name') %></th>
      <th><%= t('activerecord.attributes.hotel.email') %></th>
      <th><%= t('activerecord.attributes.hotel.address') %></th>
      <th><%= t('activerecord.attributes.hotel.phone') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @hotels.each do |hotel| %>
      <tr>
        <td><%= hotel.name %></td>
        <td><%= hotel.email %></td>
        <td><%= hotel.address %></td>
        <td><%= hotel.phone %></td>
        <td><%= link_to t('actions.show'), hotel %></td>
        <td><%= link_to t('actions.edit'), edit_hotel_path(hotel) %></td>
        <td><%= link_to t('actions.remove'), hotel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/hotels/new.html.erb
<h1 class="col-md-offset-5"><%= t('title.hotel.new') %></h1>
<%= render 'form' %>

app/views/hotels/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong><%= t('activerecord.attributes.hotel.name') %>:</strong>
  <%= @hotel.name %>
</p>
<p>
  <strong><%= t('activerecord.attributes.hotel.email') %>:</strong>
  <%= @hotel.email %>
</p>
<p>
  <strong><%= t('activerecord.attributes.hotel.address') %>:</strong>
  <%= @hotel.address %>
</p>
<p>
  <strong><%= t('activerecord.attributes.hotel.phone') %>:</strong>
  <%= @hotel.phone %>
</p>
<p>
  <strong><%= t('activerecord.attributes.hotel.bio') %>:</strong>
  <%= @hotel.bio %>
</p>
<%= link_to t('actions.edit'), edit_hotel_path(@hotel) %> |
<%= link_to t('actions.back'), hotels_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <title>WebHotel</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_for @room, :html => {:class => "form-horizontal"} do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :number, class: 'col-md-3 control-label' %>
    <div class="col-md-6">
      <%= f.number_field :number, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :floor, class: 'col-md-3 control-label' %>
    <div class="col-md-6">
      <%= f.number_field :floor, class: 'form-control' %>
    </div>
  </div>
  <%= f.submit t('actions.save'), class: 'btn btn-success col-md-3 col-md-offset-3' %>
  <%= link_to t('actions.back'), rooms_path, class: 'btn btn-default col-md-3' %>
<% end %>

app/views/rooms/edit.html.erb
<h1 class="col-md-offset-5"><%= t('title.room.edit') %></h1>
<%= render 'form' %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>
<h1><%= t('title.room.index') %></h1>
<%= link_to t('title.hotel.new'), new_room_path, class: 'btn btn-primary' %>
<table class="table table-condensed">
  <thead>
    <tr>
      <th><%= t('activerecord.attributes.room.hotel') %></th>
      <th><%= t('activerecord.attributes.room.number') %></th>
      <th><%= t('activerecord.attributes.room.floor') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.number %></td>
        <td><%= room.floor %></td>
        <td><%= link_to t('actions.show'), room %></td>
        <td><%= link_to t('actions.edit'), edit_room_path(room) %></td>
        <td><%= link_to t('actions.remove'), room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rooms/new.html.erb
<h1 class="col-md-offset-5"><%= t('title.room.new') %></h1>
<%= render 'form' %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong><%= t('activerecord.attributes.room.hotel') %>:</strong>
  <%= @room.hotel.name %>
</p>
<p>
  <strong><%= t('activerecord.attributes.room.number') %>:</strong>
  <%= @room.number %>
</p>
<p>
  <strong><%= t('activerecord.attributes.room.floor') %>:</strong>
  <%= @room.floor %>
</p>
<%= link_to t('actions.edit'), edit_room_path(@room) %> |
<%= link_to t('actions.back'), rooms_path %>